### ISSUE TITLE
pip install on ubuntu 16.04 failing on qpid-python

### ISSUE THREAD

**Issue by rsignell-usgs** [friedrichknuth/ooi_local_processing#2]
On ubuntu 16.04, 
```
 pip install -r requirements.txt
```
bombs out on this package:
```
Collecting qpid-python==0.32.1 (from -r requirements.txt (line 21))
  Using cached qpid-python-0.32.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-05iz4c1m/qpid-python/setup.py", line 42
        raise DistutilsFileError, \
                                ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-05iz4c1m/qpid-python/
```

**Comment by rsignell-usgs** [comment]
@friedrichknuth , oh, is this python 2?

**Comment by friedrichknuth** [comment]
Yes - python 2.

Do you have this issue with the mi-instrument or ion-functions requirements.txt, or both?

**Comment by rsignell-usgs** [comment]
Yes, now that I realize that this is python 2, I can build an `mi` environment that comes up as a selectable kernel in Jupyter thusly:
```
conda env create -c mi_env.yml
```
where `mi_env.yml` is:
```
name: mi
channels:
  - ooi
  - conda-forge
  - defaults
dependencies:
  - python=2
  - mi-instrument
  - ion-functions
  - nb_conda_kernels
```
